<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <RootNamespace>Intelbras.CameraCenter.App</RootNamespace>
    <AssemblyName>Intelbras-Camera-Center</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Version>1.0.0</Version>
    <Authors>MukaSanches</Authors>
    <Product>Intelbras Camera Center</Product>
    <Description>Modern Windows VMS/NVR client for Intelbras-compatible cameras, DVRs and NVRs.</Description>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="WPF-UI" Version="4.3.0" />
    <PackageReference Include="LibVLCSharp.WPF" Version="3.10.1" />
    <PackageReference Include="VideoLAN.LibVLC.Windows" Version="3.0.24" />
  </ItemGroup>
</Project>
